### ISSUE TITLE
Plutonium ingot/dust isotope separator recipe

### ISSUE THREAD

**Issue by D3nnis3n** [turbodiesel4598/NuclearCraft#143] opened 2017-10-02 02:37 UTC
Hey, to unify the ore Generation i use the *Metals (BaseMetals, ModernMetals) Suite for Generation of common ores - this includes Plutonium (which is supposed to drop in piles additional to uranium in your mod, i think?), and uranium. Despite boron and Thorium i do not allow your ores to spawn.

Because of that, uranium is also not dropping Plutonium piles, at least this is what i think now.
That makes it impossible to create some fuels, as of no Plutonium available. But we do have Plutonium ores spawned, which could be used to create Plutonium needing fuels, but those are not recipe-compatible.

Anything you could do about that maybe making a compatible recipe or letting the piles drop from other mods ores, too?

**Comment by turbodiesel4598** [comment] 2017-10-02 12:39
Is this 1.7.10 you are talking about? Because in 1.10-12.2, there isn't any plutonium ore in NC. Either way, the lack of plutonium ore doesn't really matter - you are supposed to generate plutonium and the rarer elements from fission reactions - you can obtain plutonium from depleted uranium and neptunium fuels.

**Comment by D3nnis3n** [comment] 2017-10-02 16:33
Yeh, that's embarassing for me now. (Using 1.12.2) Anyways, so i at least DO have a bug (hopefully) to report: I do not have any recipes in JEI for the Fuel Reprocessor - so i was wondering how to make Plutonium and only found that seemingly old Information in Google. I just tried out what you said - and yeah, that does indeed work. I'm sorry :(

I also had a nice experience today when setting up my first reactor (want to switch from big reactors, do like your mod much, but am missing the ability to create steam, as i also got mekanism with great steam turbines but a too op fusion reactor), it just went to Lava :D Had to search all removed blocks and replace them. That was even harder to repair than an Explosion.

But nevertheless i would like the option to somehow also be able to use the basemetals Plutonium ore (as we do let it spawn for tinkers construct usage). I read that you indeed CAN find it naturally - but REALLY REALLY rare. And that's what it is in my pack. You find one ore block per chunk.

Also, i got a little question: It seems as your mod adds Lithium as ore. Mekanism Fusion reactors do use Lithium, but you have to make it with solar Evaporation Towers. So with your mod mekanism Fusion reactors get even easier. Is there some way to make your Lithium dust incompatible or would you recommend disabling mekanism reactors or something like that? I like to Balance out as much as possible, but i'm new to crafttweaker.

**Comment by D3nnis3n** [comment] 2017-10-02 17:13
I also saw you have manganese and Zirconium Ingots, but no ores for that. How are those generated and can we disable this, didn't found something in the config. Zirconium and manganese is both added as ore by BaseMetals / ModernMetals.

**Comment by turbodiesel4598** [comment] 2017-10-03 14:12
> I do not have any recipes in JEI for the Fuel Reprocessor when pressing R on the Plutonium thingies
That might be because you're looking for the recipes for the normal lumps of plutonium, while the fuel reprocessor only produces the tiny lumps, 9 of which produce a normal lump.
> it just went to Lava :D
Sounds like you generated quite a bit of heat :P - oh well, a lava mess is better than a dead base, right?
> i would like the option to somehow also be able to use the basemetals Plutonium ore
Should be easy, as long as that mod also adds plutonium dust/ingots... does it?
> There are a couple of options you have, but probably the best thing to do would be to download CraftTweaker and add a script that removes the NuclearCraft lithium from the ore dictionary - that would make it impossible to use NC lithium in Mek recipes.

**Comment by D3nnis3n** [comment] 2017-10-03 15:18
BaseMetals and ModernMetals is a Suite trying to add every used Ore in one mod and makes all of them compatible with the most know tech mods, e.g. TiC (with all tools), Mekanism (with all items for 5x Ores), IC2 (with all items), and TE. It also adds all the vanilla building materials in that Ore, tools and Armor. Yes it does have ingots and dusts - and much more.

As for JEI: Yes, that could be correct. It's pretty confusing when pressing r Ten times while get the feeling you are going in a circle and can't find the Source.

**Comment by D3nnis3n** [comment] 2017-10-03 15:22
As for Lava. I tend to think that repairing the reactor and finding all the broken blocks is more mean, at least in Creative. It surely is better than a big Explosion, but nothing bigger should have had happened when exploding anyway as we Surround reactors with a 5-10 blocks thick Layer of highly blast resistent and absorbing blocks.

**Comment by D3nnis3n** [comment] 2017-10-03 15:28
As for the lithium: Would that also prevent the lithium being mitten down to compatible Liquid one - as only the liquid one gets used IIRC. (Didnt use their Fusion for a long time and this is all to encourage to use yours)

Thanks die your Kind answers. I try to find the config to disable those Drops (on First look, didnt). Ja rhodocrosite oredicted to manganesedust? Or is there the same Problem that i can't use the Ore? Zirconium seems to have dust which is oredicted.

Thanks for the Great mod, i also like all those Utility machines and the bin. :) looking forward dir Steam production to make my build even more realistic :)

**Comment by D3nnis3n** [comment] 2017-10-04 06:27
So i just checked, manganese oxide dust is locked out, when dropping rhodosomething is disabled. You might should make it so oredicted manganesedust can be oxided / oxidized like the fuels can. That would fit an make it possible to gain without your Drops enabled.

**Comment by D3nnis3n** [comment] 2017-10-04 19:14
@turbodiesel4598 Should i create another issue for the missing drop Options and manganese not being availalbe when disabled because of no oxidizing recipe?

**Comment by turbodiesel4598** [comment] 2017-10-07 18:01
> nothing bigger should have had happened when exploding anyway as we Surround reactors with a 5-10 blocks thick Layer of highly blast resistent and absorbing blocks

Should I make it a config option to have the reactor explode rather than melt into lava then?
> Would that also prevent the lithium being mitten down to compatible Liquid one

No, as you can only melt down lithium-6 or lithium-7 in NC. You could also just remove the NC lithium ore altogether.
> Ja rhodocrosite oredicted to manganesedust

No, rhodochrosite is oreDicted to 'gemRhodochrosite', and rhodochrosite dust is oreDicted to 'dustRhodochrosite'. [Rhodochrosite dust then smelts into manganese dust.](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/vanilla/FurnaceRecipeHandler.java#L25)
> You might should make it so oredicted manganesedust can be oxided / oxidized like the fuels can

It can be - [manganese ingots can be oxidised into manganese oxide ingots](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/processor/InfuserRecipes.java#L24), and [manganese dust can be oxidised into manganese oxide dust.](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/recipe/processor/InfuserRecipes.java#L28)
> i can not find an config Option to disable those Drops anyway, could you tell me how they're supposed to be called?

The problem is that there is a minor localisation error, but they should definitely be there, just called 'ore_drops', I think.

**Comment by D3nnis3n** [comment] 2017-10-07 18:14
Sorry again for my spamming. I'm just exicted.

>> Should I make it a config option to have the reactor explode rather than melt into lava then?
Well, reactors don't usually explode in reallife if there is not any Output of gas. So i think your mod sticks to reality and this is fine. You don't Need to add this Option just for me. I couldn't even tell if i would use it as i would Need to compare how devastating both are. For the Servers good the meltdown Happening atm seems better, even tough more tedious.

>> No, as you can only melt down lithium-6 or lithium-7 in NC. You could also just remove the NC lithium ore altogether.

Yeh, but Mekanism allows your dust to be molten down into usual Lithium as soon as it detects it. Would removing the oredict stop mekanism from detecting it as valid for smelting down to liquid? I hope you can understand me, i'm not a native english Speaker and try my best to make it comprehensable.

>> No, rhodochrosite is oreDicted to 'gemRhodochrosite', and rhodochrosite dust is oreDicted to 'dustRhodochrosite'. Rhodochrosite dust then smelts into manganese dust.
I see. But unfortunatley the BaseMetals manganese is not recognized, neither as dustManganese, nor as ingotManganese. I'll attach you a Screen as proof of oredict entry: https://ibb.co/ixX7fb

>> The problem is that there is a minor localisation error, but they should definitely be there, just called 'ore_drops', I think.

Yes:
    # gui.config.ores.ore_drops.comment
    B:ore_drops <
        true
        true
        true
        true
        true
     >

But which one is which?

**Comment by D3nnis3n** [comment] 2017-10-07 18:17
Forget my text concerning manganese. It seems to suddenly began working after the latest *Metals Update.

**Comment by turbodiesel4598** [comment] 2017-10-07 18:34
> You don't Need to add this Option just for me

It's a really easy thing to add so I don't mind - some people may like it better than the lava... who knows :)
> Would removing the oredict stop mekanism from detecting it as valid for smelting down to liquid?

Yes, it should. Sorry, I didn't realise that you had to melt down lithium in Mekanism, so I thought you were talking about the NC melter :P
> But which one is which?

[The order is rhodochrosite, beryllium dust, zirconium dust, fluorite, sulfur :)](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/resources/assets/nuclearcraft/lang/en_US.lang#L935-L936)

**Comment by D3nnis3n** [comment] 2017-10-07 18:38
No, you can't meltdown Lithium in mekanism. You create it by evaporating something in a solar Tower. So you can only CREATE it in liquid and THEN make it solid. :)

Thank you for the help with the Drops :) So all of this issue left really is the Plutonium compat. :D Thanks for your kind help :) You might should include the order in the config, like you do with all the other Things.

**Comment by turbodiesel4598** [comment] 2017-10-09 09:51
> You might should include the order in the config, like you do with all the other Things.

Yeh, it does have a description, but it just doesn't show due to that localisation error.

**Comment by D3nnis3n** [comment] 2017-10-11 10:34
@turbodiesel4598 
From which blocks do Fluorite and Beryllium drop?

**Comment by D3nnis3n** [comment] 2017-10-11 19:00
You could add Support for JEI-BlockDrops, then it would be easier to see, i still couldn't find out from which blocks those drop :D

**Comment by turbodiesel4598** [comment] 2017-10-11 19:13
[Beryllium drops from coal ore and fluorite drops from lapis lazuli ore.](https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/handler/DropHandler.java#L34-L39)

**Comment by D3nnis3n** [comment] 2017-10-11 19:15
That explains why i got nearly no Fluorite :D

**Comment by turbodiesel4598** [comment] 2017-10-11 19:23
Yeh, it's pretty rare, but you should end up having about 1 Fluorite for every 3 pieces of Lapis.

**Comment by D3nnis3n** [comment] 2017-10-11 19:26
Yeh. That would work out, if Lapis wouldn't be 2 per chunk here. :D 
Does this have any real base like the other ores? Beryllium from Coal and Fluorite from Lapis?

Lapis is 

Na,Ca)8Al6Si6O24(S,SO)4 | Na,Ca)8Al6Si6O24(S,SO)4
-- | --
Na,Ca)8Al6Si6O24(S,SO)4

That would work out, if Lapis wouldn't be 2 per chunk here. :D 
Does this have any real base like the other ores? Beryllium from Coal and Fluorite from Lapis?

Lapis is (Na,Ca)8Al6Si6O24(S,SO)4, so no F in there.
Coal also seems to have nothing in common with Be.

**Comment by turbodiesel4598** [comment] 2017-12-05 03:38
It's not necessarlity meant to be realistic - I just didn't want to add any new ores, because it's a hassle for people who have already generated their world to then obtain the new materials, so I just added extra drops to vanilla ores :)

And the plutonium issue will be fixed for the next update :)

**Closed by turbodiesel4598** 2017-12-05 03:38 UTC
Labels: addition
