### ISSUE TITLE
Compatibility with Mekanism?

### ISSUE THREAD

**Issue by ngreatorex** [turbodiesel4598/NuclearCraft#14] opened 2016-02-11 20:10 UTC
I'm trying to use NuclearCraft 1.6c with Mekanism 8.1.8 and I'm getting an exception:

```
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: nc/tile/generator/TileFusionReactor
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: nc/tile/generator/TileFusionReactor
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: nc.tile.generator.TileFusionReactor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: nc/tile/generator/TileGenerator
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more
Caused by: java.lang.ClassNotFoundException: nc.tile.generator.TileGenerator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
```
The exception does not occur with either Mekanism or NuclearCraft on their own. I haven't tried older versions of Mekanism. Is NuclearCraft compatible with Mekanism? If so, what versions have been tested to work?

I've attached the full crash log, so you can see the mod versions etc:
[crash-2016-02-11_19.55.30-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/127047/crash-2016-02-11_19.55.30-client.txt)

Launcher output is at:
https://gist.github.com/ngreatorex/7df195fabb8e9ce6bce1

**Comment by spannerman79** [comment] 2016-02-12 17:48
This is an issue on your end - lauches correctly with me

https://paste.ee/p/NbYWT

**Comment by ngreatorex** [comment] 2016-02-12 18:21
I've experimented some more, and have discovered that the error goes away if I either:

- Include CoFHCore in mods folder
- Don't include NEI (as I believe @spannerman79 has shown)

So it seems that the combination of NuclearCraft, NEI and Mekanism requires CoFHCore, even though none of them require it individually...

**Comment by spannerman79** [comment] 2016-02-12 18:26
> Don't include NEI (as I believe @spannerman79 has shown)

Its actually adding NEI.  Didn't even need to add CoFHCore.  Mekanism doesn't need CoFHCore.

https://paste.ee/p/OwnSf

**Comment by turbodiesel4598** [comment] 2016-02-19 11:24
I'll look into it.

**Comment by turbodiesel4598** [comment] 2016-02-21 15:25
I've removed all CoFH dependencies - hopefully that helps in some way.

**Comment by turbodiesel4598** [comment] 2016-02-28 19:03
The mod has just been updated - there are no more CoFH dependencies, as I said. Hopefully this bug now doesn't exist and we can close this.

**Comment by turbodiesel4598** [comment] 2016-03-05 17:42
Well, looks like the bug's still there :/ Perhaps letting aidancbrady would help?

**Comment by th4umiel** [comment] 2016-04-02 23:20
With latest version of both mods (nuclearcraft 1.6e and mekanism 8.1.9) Mekanism oregen doesn't work (didn't pay attention to tin and copper, but definitely I couldn't find osmium, even "cheating" with the digital miner). After removing nuclearcraft the issue disappeared. 
It's a shame because I waited for months in order to insert NC in the new modpack :(

**Comment by turbodiesel4598** [comment] 2016-04-10 16:10
There seems to be some very strange conflict going on - it's not obvious to me why there is an issue...

**Comment by turbodiesel4598** [comment] 2016-07-22 16:14
I think there's a possibility this bug could be fixed - I changed the names of the tile entities a bit so that there should no longer be any chance of conflicts. This has not been confirmed, though.

**Closed** 2016-09-23 15:53 UTC
