### ISSUE TITLE
Errors from crafttweaker NuclearCraft-2.8--1.12.2

### ISSUE THREAD

**Issue by Trixz2018** [turbodiesel4598/NuclearCraft#206] opened 2018-01-03 06:49 UTC
so i downloaded the latest jar you just released and i got this when i loaded into my world from crafttweaker.
[POSTINITIALIZATION][CLIENT][ERROR] system: manufactory is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: isotope_separator is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: decay_hastener is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: fuel_reprocessor is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: alloy_furnace is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: infuser is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: melter is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: supercooler is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: electrolyser is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: irradiator is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: ingot_former is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: pressurizer is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: chemical_reactor is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: salt_mixer is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: crystallizer is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: dissolver is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: fission is already defined in that package
[POSTINITIALIZATION][CLIENT][ERROR] system: fusion is already defined in that package

**Comment by OneEyeMaker** [comment] 2018-01-03 06:54
@turbodiesel4598 
Seems like CraftTweaker handlers registered twice.

**Comment by turbodiesel4598** [comment] 2018-01-03 13:56
That is very strange, as I didn’t change any CraftTweaker integration code with this update, but I’ll look into it - does this error crash the game?

**Comment by OneEyeMaker** [comment] 2018-01-03 15:15
@turbodiesel4598 
Try to remove annotation ```ZenRegister``` from all classes, which *manually registered* as handlers for CraftTweaker.
Reason: https://github.com/jaredlll08/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/annotations/ZenRegister.java#L5-L8

**Comment by Trixz2018** [comment] 2018-01-03 16:20
@turbodiesel4598 no it didn't crash the game, thank goodness as i haven't changed any recipes yet. All you get is that error showing ingame and i figured you should know about it.

**Comment by Trixz2018** [comment] 2018-01-03 19:05
So i just downloaded the updated 2.8 jar and still getting the same error

**Comment by turbodiesel4598** [comment] 2018-01-03 19:54
Yeh, I didn't fix the bug in that release - that was a fix for a crash that was occurring with reactor ports.

**Comment by turbodiesel4598** [comment] 2018-01-04 05:51
Ah, ok, I think I found the issue - it's only appeared as of the latest CraftTweaker update. Will get a fix out when I can :)

**Comment by jaredlll08** [comment] 2018-01-04 18:31
Actually, the issue is that you are registering your handlers twice, you are using ZenRegister, and then manually registering here (too late to be called in a sciprt may I add)
https://github.com/turbodiesel4598/NuclearCraft/blob/master/src/main/java/nc/integration/crafttweaker/NCCraftTweaker.java#L16-L35

**Comment by turbodiesel4598** [comment] 2018-01-05 03:38
Cheers @jaredlll08 , sorted it. It's only recently that the message has appeared in chat though right? Because that mistake's been there for some time :P

**Comment by turbodiesel4598** [comment] 2018-01-05 03:47
[Fixed in version 2.8b :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2516959)

**Closed by turbodiesel4598** 2018-01-05 03:47 UTC
Labels: 1.12.2, bug

**Comment by Trixz2018** [comment] 2018-01-05 05:45
thank you so much!

**Comment by turbodiesel4598** [comment] 2018-01-05 06:01
No prob!
