### ISSUE TITLE
Crash when Creating WitherBoss (Spongepowered)

### ISSUE THREAD

**Issue by YOYOK9** [turbodiesel4598/NuclearCraft#89] opened 2017-04-26 21:55 UTC
So I'm aware this has been brought up already But my issue is caused by the creation of a wither boss... not sure how the 2 are connected but everytime someone tries to spawn one the server crashes and gives the crash.

Sponge thread:
https://forums.spongepowered.org/t/crash-on-wither-spawn/18603

Crash:
https://pastebin.com/WH39GXz9

**Comment by turbodiesel4598** [comment] 2017-04-27 01:44
Man, I don't know... perhaps the people at Sponge could be a little more specific in what I'm apparently doing wrong to break their API all the time. I just can't understand how the issue is on NC's end when it runs fine without Sponge.

**Comment by YOYOK9** [comment] 2017-04-27 15:25
Have you tried contacting them about it?

**Comment by turbodiesel4598** [comment] 2017-04-27 15:29
I will do :)

**Comment by YOYOK9** [comment] 2017-04-27 17:02
Cool! Love your mod and really dont want to have to remove it from my modpack :(

**Comment by MoeBoy76** [comment] 2017-04-27 21:50
not sure what is happening exactly but it's calling the below recursively until the JVM reaches a StackOverflow
https://github.com/turbodiesel4598/NuclearCraft/blob/1.10.2/src/main/java/nc/tile/NCTile.java#L58

**Comment by turbodiesel4598** [comment] 2017-05-06 23:37
Should be fixed in the latest version  2.2 :)

**Closed by turbodiesel4598** 2017-05-06 23:37 UTC
Labels: 1.10.2, crash
