### ISSUE TITLE
Client crash, looks like a NuclearCraft error

### ISSUE THREAD

**Issue by indoorsNB** [turbodiesel4598/NuclearCraft#74] opened 2017-01-29 01:22 UTC
I don't know what happened, but when I join to my server, client crash. I restart the game and join the server, crash again, same problem. I think it is nuclearCraft's bug.
http://pastebin.com/b5ufke3P

**Comment by indoorsNB** [comment] 2017-02-01 05:11
This error let my client can't join the server

**Comment by turbodiesel4598** [comment] 2017-03-05 21:16
Can you join single player worlds?

**Comment by indoorsNB** [comment] 2017-03-09 16:12
Yes, single player is working

**Comment by indoorsNB** [comment] 2017-03-09 16:20
After I delete the world file on server and restart, I can join my server again. But got kick out after a few minutes and can't join server anymore, but I lost the logs : (

**Comment by turbodiesel4598** [comment] 2017-03-14 01:47
Hmm - might be a similar issue to this one: https://github.com/SleepyTrousers/EnderZoo/issues/45 ... I'll look for a fix, but I'm not exactly sure what that may be.

**Comment by indoorsNB** [comment] 2017-03-14 02:03
thank you  👍

**Comment by turbodiesel4598** [comment] 2017-04-24 13:49
The only info I can find on this is that the crash is being caused by an entity ID mismatch between the server and client, and I have no control over that as Forge handles it automatically, so I can't see how this could be fixed without starting a fresh server with fresh configs. Sorry I couldn't find a better solution.

**Closed by turbodiesel4598** 2017-04-24 13:49 UTC
Labels: 1.7.10, crash, help wanted
