### ISSUE TITLE
Crash in Manufactory GUI

### ISSUE THREAD

**Issue by kungfunick123** [turbodiesel4598/NuclearCraft#180] opened 2017-11-22 16:27 UTC
So I'm not the only one with this issue, I've had a few other people experience it. When doing basically anything except taking a finished product out of the manufactory and pressing escape (and sometimes even that does it) my game just instantly crashes and says it had an error rendering the screen. Also I'm using AllTheMods modpack, its on NuclearCraft 2.5A. This issue also seems to happen after having sat in the interface of any nuclearcraft machine for too long

https://gist.github.com/kungfunick123/16d62f7934f8cc438356acf3ae50fd49

**Comment by turbodiesel4598** [comment] 2017-12-06 04:30
I think this is now fixed - as you say, this was a common issue, and was caused by me basically not knowing what I was doing :P

**Closed by turbodiesel4598** 2017-12-06 04:30 UTC

**Comment by Yamiji** [comment] 2017-12-06 16:05
You say it's fixed, but there's no updated version available anywhere. Can we get ETA for the fix to get uploaded?

**Comment by kungfunick123** [comment] 2017-12-06 16:05
^

**Comment by turbodiesel4598** [comment] 2017-12-06 17:05
Hmmm... I don't really have an exact ETA as I don't know how long it will take for me to fix all these bugs that have been piling up over the last couple of months - I'm working on it most of the day now though, so I guess it's really just 'in as long as it takes'.

**Comment by turbodiesel4598** [comment] 2017-12-09 18:17
I have a new ETA for you - now! [NC 2.6 is now available to download](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files) :)
