### ISSUE TITLE
Question/enhancement: Dense Cobble generator malfunctions?

### ISSUE THREAD

**Issue by sharkbite3105** [turbodiesel4598/NuclearCraft#257] opened 2018-02-23 11:19 UTC
I recently started using FTB revelation modpack(1.5.0 currently) and crafted a dense cobble generator, the tooltip states that it creates 128 cobblestone/s could this be clarified? it seems to only make 10 stacks about every minute or so, this observation was made by itemducting into an iron chest.

**Comment by turbodiesel4598** [comment] 2018-03-16 02:29
Try putting a chest right next to the cobble generator - it should push out the correct amount of cobble. If not, then we have a bug. If not, then the itemduct doesn't seem to be pulling out all of the cobble being produced.

**Comment by sharkbite3105** [comment] 2018-03-17 02:19
yep did the same thing with thte chest next to it, timed it this time, 10 stacks every 50 seconds-ish, the helium collectors do a similar thing except I dont have that at dense just compact, 160 buckets on a similar time interval

**Comment by sharkbite3105** [comment] 2018-03-17 02:25
![2018-03-16_22 22 51](https://user-images.githubusercontent.com/36560028/37550744-fc24b620-2968-11e8-852d-f491a8ee24e2.png)
![2018-03-16_22 23 41](https://user-images.githubusercontent.com/36560028/37550745-fc311c80-2968-11e8-8f50-ac7c8708e8eb.png)

**Comment by turbodiesel4598** [comment] 2018-03-17 03:58
That is very bizarre... I am not able to recreate this, either with the mod installed on its own or in FTB Revelation (1.6.0). Which version of NC is 1.5.0 using?

**Comment by sharkbite3105** [comment] 2018-03-17 06:42
1.5.0 FTB Revelation uses nc 2.9d

**Comment by turbodiesel4598** [comment] 2018-03-17 13:54
What if you create a brand new world and just place one next to a chest? This is a tad tricky because, as I said, I'm not having the issue.

**Comment by sharkbite3105** [comment] 2018-03-17 16:26
alright I tried it in my singleplayer testing world and its faster by a factor of 10, so it seems to be closer to what your tooltip indicates (10 stacks every 5 seconds). But with me being the only person on a server running at 20 tps it still does the 10 stacks every 50 seconds. When you place the chest, is it continuously placing 2 stacks in every second?

**Comment by turbodiesel4598** [comment] 2018-03-17 17:50
No - to minimise lag, the cobble gen (and those other similar blocks) updates every 5 seconds, so the dense produces 10 stacks every 5 seconds by default. I can only imagine that something about your world is causing it to slow down... not sure what that could be though.

**Comment by sharkbite3105** [comment] 2018-03-17 21:27
alright so when the "internal buffer" of the generator is "full" it searches for a chest to kick it to got it, still doesn't explain the 50 seconds thing on our server though, like you said bizarre.

**Comment by turbodiesel4598** [comment] 2018-04-15 16:59
Yeh, as I said before, I'm really not sure why that is happening to you - just really bizarre, but I will close this issue as I can't reproduce it (you seemed to show it was an issue specific to that world) and there isn't anything I can do to fix it.

**Closed by turbodiesel4598** 2018-04-15 16:59 UTC
Labels: bug
