### ISSUE TITLE
Crash server when placing down alloy furnace (Spongepowered)

### ISSUE THREAD

**Issue by Rongmario** [turbodiesel4598/NuclearCraft#86] opened 2017-04-18 23:40 UTC
https://hastebin.com/tuteximixa.sql

**Comment by turbodiesel4598** [comment] 2017-04-19 01:59
I'm not exactly sure how to fix this, as the problem seems to be on Sponge's side, and I don't know anything about Sponge - you may want to go ask them what the issue is.

**Comment by Rongmario** [comment] 2017-04-22 20:19
Gotcha, will reference it here.

**Comment by Rongmario** [comment] 2017-04-22 20:24
#https://github.com/SpongePowered/SpongeForge/issues/1457

**Comment by Towsty** [comment] 2017-04-27 17:43
Not to add to the sponge train here but the same issue exists when place coal in a manufactory.

**Comment by turbodiesel4598** [comment] 2017-04-27 17:58
I've commented on a thread on the sponge website about these issues, and hopefully someone who knows about sponge replies.

**Comment by turbodiesel4598** [comment] 2017-05-06 23:37
Should be fixed in the latest version  2.2 :)

**Closed by turbodiesel4598** 2017-05-06 23:37 UTC
Labels: 1.10.2, crash

**Comment by Rongmario** [comment] 2017-05-07 17:42
Good one turbo!
