### ISSUE TITLE
reactor needs massive server performance

### ISSUE THREAD

**Issue by ValonInc** [turbodiesel4598/NuclearCraft#205] opened 2018-01-02 10:13 UTC
![image](https://user-images.githubusercontent.com/30478519/34480504-1147d064-efad-11e7-8b7c-242feb7cd557.png)
the reactor need 200 (idk whats that unit) /t
normal machines need ~10-20

**Comment by Fatmice** [comment] 2018-01-05 18:18
@ValonInc Which mod gave your that visualization of ticking profile?  The unit is in microseconds.

**Comment by LokeYourLord** [comment] 2018-01-11 10:40
@Fatmice The mod is called LagGoggles: https://minecraft.curseforge.com/projects/laggoggles

**Comment by turbodiesel4598** [comment] 2018-03-16 01:02
Ok, after trying a few things, I don't think there's too much I can do until MC 1.13 comes about. The problem is with the way multiblocks are checked in NC, which I can't fix now without breaking everybody's reactors. When 1.13 arrives, I'm plannin an overhaul of the multiblock system which should almost certainly fix any of these lag issues :)

**Closed by turbodiesel4598** 2018-03-16 01:02 UTC
Labels: 1.12.2, bug
