### ISSUE TITLE
Crash when inserting Depleted Cell

### ISSUE THREAD

**Issue by GrazzMan** [turbodiesel4598/NuclearCraft#65] opened 2016-10-06 02:40 UTC
Accidentally added Depleted LEU-235 to Fission Reactor. Crashed Server completely. Had to edit and remove block in MCEdit to get server to start again. Using Ver 1.9c in MC 1.7.10
[crash-2016-10-05_18.34.40-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/512760/crash-2016-10-05_18.34.40-server.txt)

Time: 10/5/16 6:34 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: -1
    at nc.tile.generator.TileFissionReactor.doesFuelMatchDepleted(TileFissionReactor.java:668)
    at nc.tile.generator.TileFissionReactor.fuel(TileFissionReactor.java:679)
    at nc.tile.generator.TileFissionReactor.func_145845_h(TileFissionReactor.java:115)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at nc.tile.generator.TileFissionReactor.doesFuelMatchDepleted(TileFissionReactor.java:668)
    at nc.tile.generator.TileFissionReactor.fuel(TileFissionReactor.java:679)
    at nc.tile.generator.TileFissionReactor.func_145845_h(TileFissionReactor.java:115)
    at net.minecraft.world.World.func_72939_s(World.java:1939)

**Comment by turbodiesel4598** [comment] 2016-12-07 00:06
I'm finally on the case :)

**Comment by turbodiesel4598** [comment] 2016-12-07 00:48
Actually, I can't recreate this... can you either recreate this or remember how this happened?

**Comment by GrazzMan** [comment] 2016-12-07 02:48
It was a ME export bus with depleted as the filter. Not at my system for a few days, but was ME driven.

**Comment by turbodiesel4598** [comment] 2016-12-07 03:54
Well, that seems strange, considering that I can't even export depleted cells (or any non-valid item, in fact) to the controller. Perhaps the issue is fixed in 1.9d?

**Comment by turbodiesel4598** [comment] 2017-04-18 19:27
[Fixed in version 1.9f :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2408593)

**Closed by turbodiesel4598** 2017-04-18 19:27 UTC
Labels: 1.7.10, crash
