### ISSUE TITLE
Helium collector Crash

### ISSUE THREAD

**Issue by ProxyPlayerHD** [turbodiesel4598/NuclearCraft#123] opened 2017-07-15 06:41 UTC
just [this](https://pastebin.com/bQSz4Zg8)

**Comment by turbodiesel4598** [comment] 2017-07-15 19:59
Did it just crash when you placed it? What caused the crash?

**Comment by ProxyPlayerHD** [comment] 2017-07-16 14:53
version 2.3 it crashed in few seconds after i placed it.

**Comment by turbodiesel4598** [comment] 2017-07-16 18:08
I've had two reports of this now - will look into it and get a fix out.

**Comment by turbodiesel4598** [comment] 2017-09-20 02:32
[Fixed in version 2.4 :)](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files)

It was caused by the collector trying to push helium into machines that couldn't accept it.

**Closed by turbodiesel4598** 2017-09-20 02:32 UTC
Labels: 1.10/11.2, crash
