### ISSUE TITLE
NullPointerException Radiation

### ISSUE THREAD

**Issue by Blatts12** [turbodiesel4598/NuclearCraft#477] opened 2019-03-22 14:06 UTC
Created new world and after few secs game crashed

https://paste.dimdev.org/makihemoza.mccrash

**Comment by liach** [comment] 2019-03-22 14:31
NuclearCraft should check the type of ray trace result before using the position in the result.

https://github.com/turbodiesel4598/NuclearCraft/blob/f186fbeaf8c432a0644f817cb55f1780785c1095/src/main/java/nc/radiation/RadiationRenders.java#L154

**Comment by liach** [comment] 2019-03-22 14:32
Ah, this is actually a duplicate of #476

**Comment by turbodiesel4598** [comment] 2019-03-22 16:23
Fixed - will get a new build out now!

**Closed by turbodiesel4598** 2019-03-22 16:23 UTC
Labels: 1.12.2, crash
