### ISSUE TITLE
NuclearCraft-2.8d - nuclearcraft:water_source - ticking entity crash when pushing in to other machines.

### ISSUE THREAD

**Issue by Electrofried** [turbodiesel4598/NuclearCraft#220] opened 2018-01-20 14:19 UTC
As per title. The infinite water source will crash a server when placed next to specific machines.
Have attached crash log. In this case it was a forestry carpenter that was attached that caused the issue.
[crash-2018-01-21_02.47.19-server.txt](https://github.com/turbodiesel4598/NuclearCraft/files/1648873/crash-2018-01-21_02.47.19-server.txt)

**Comment by turbodiesel4598** [comment] 2018-01-20 21:45
When I get back to my laptop I’ll try to recreate this - it looks like what’s actually throwing the error is Tesla, which is very bizarre...

**Comment by turbodiesel4598** [comment] 2018-01-20 22:34
So yeh, couldn't recreate this without Tesla - do you mind seeing if you can recreate the issue without Tesla installed? Perhaps just disable it temporarily and start a new creative world. I will do the same now with Tesla installed.

**Comment by turbodiesel4598** [comment] 2018-03-16 16:21
Ok, I think this is a duplicate of another issue that was posted - Tesla have fixed this on their side, and I have put in extra checks to try to prevent it on mine.

**Closed by turbodiesel4598** 2018-03-16 16:21 UTC
Labels: 1.12.2, crash
