### ISSUE TITLE
Crash after updating to 2.18

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [turbodiesel4598/NuclearCraft#573] opened 2019-08-11 09:12 UTC
Happens a few seconds after world starts loading. Seems to be related to Ender IO Conduits

https://paste.dimdev.org/ewefatuvek.mccrash

**Comment by ToMe25** [comment] 2019-08-11 09:18
this is basically a duplicate of #572.

**Comment by turbodiesel4598** [comment] 2019-08-11 20:42
Fixed! Will upload to CF shortly :)

**Closed by turbodiesel4598** 2019-08-11 20:42 UTC
Labels: 1.12.2, crash
