### ISSUE TITLE
[1.12.2](client side) NuclearFurnace cannot open gui

### ISSUE THREAD

**Issue by yuanjie000** [turbodiesel4598/NuclearCraft#171] opened 2017-11-13 07:42 UTC
[crash](http://paste.ubuntu.com/25952578/)
forge:14.23.0.2517
NuclearCraft-2.5a--1.12.2

**Comment by Thutmose** [comment] 2017-11-15 04:26
this is a duplicate of #160

**Closed** 2017-11-15 08:50 UTC
