### ISSUE TITLE
Getting reports of large Fission Reactors causing massive timings

### ISSUE THREAD

**Issue by b0bst3r** [turbodiesel4598/NuclearCraft#27] opened 2016-04-14 13:09 UTC
https://github.com/BevoTechPack/BevoTechPack/issues/963

Please note that server runs on cauldron/thermos, we are testing on plain Forge, results to follow.

**Comment by turbodiesel4598** [comment] 2016-04-24 14:58
I think I might be able to find a way to fix this when I change up the fission reactors for the next version - at the moment, the structure is being checked if it is complete, which is probably what is causing the lag for the bigger sizes.

**Comment by turbodiesel4598** [comment] 2016-06-09 19:30
The latest versions of the mod include attempts to fix this - I will not close this until I know for sure that the problem is gone.
There is also a fission config option to further increase the number of ticks per structure check.

**Comment by b0bst3r** [comment] 2016-06-11 00:46
Ohh not sure what's going on I'm testing the update to NuclearCraft-1.7c and wanted to test the new explosion blasts on the fission reactors.  So I took a 3x3x3 and a 5x5x5 and put in MOX239 as fuel, the heat went all the way to the top and no explosion, instead TPS hit the floor, was taking ages to do anything at all even break blocks.  This was a test world with nothing else in it except for the above 2 reactors.  Upon breaking the reactor controller block everything returned to normal.

**Comment by turbodiesel4598** [comment] 2016-06-11 01:02
I already know exactly why that happened - fix should be up in a few minutes :)
By the way, do you notice any tickrate improvements?

**Comment by b0bst3r** [comment] 2016-06-11 01:11
I'll let you know after the fix lol :D

**Comment by turbodiesel4598** [comment] 2016-06-11 01:21
It's been approved:
http://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2306715

**Comment by b0bst3r** [comment] 2016-06-11 01:45
Already way ahead of you :) tested and working, I swore I heard you say you'd toned the explosions down somewhere lol :p could have fooled me :D

**Comment by turbodiesel4598** [comment] 2016-06-11 02:01
Well, they are still pretty big, but they used to be used to be a little ridiculous - just ask Thorgal :P 
I think I may tone them down a bit more though.

**Comment by turbodiesel4598** [comment] 2016-06-11 03:54
Just released another version that makes sure that there is only one explosion (in the case that the controller is not destroyed by the explosion).

**Closed** 2016-06-27 16:25 UTC
