### ISSUE TITLE
Resetting Deep dark doesn't generate Nuclearcraft ores

### ISSUE THREAD

**Issue by th4umiel** [turbodiesel4598/NuclearCraft#98] opened 2017-05-07 19:18 UTC
So, I added Nuclearcraft and Advanced Rocketry to an old save. I deleted the Deep dark dimension (extra utilities 2) folder and the Mining Dimension (Aroma1997) in order to generate your mod's ores and the ones of Advanced Rocketry. 
No problem for the ones of AR, but yours don't generate. 
In a new save no issues in the overworld or in other dimensions.
Running NuclearCraft-2.1b--1.10.2.jar

**Comment by turbodiesel4598** [comment] 2017-05-07 19:27
There's probably some new Forge event I was unaware of - I'll try to get it sorted for the next version.

**Comment by th4umiel** [comment] 2017-05-07 19:28
You are very fast in responding O.o Thanx :D

**Comment by turbodiesel4598** [comment] 2017-05-07 20:51
No prob ;)

**Comment by turbodiesel4598** [comment] 2017-05-15 19:38
Ok, I don't think the new event will help in any way - it just seems to be a way of bypassing writing one's own world gen methods. However, I have a solution: I will add a simple config option in the ores category, which is essentially just a list of all dimension numbers in which to generate ores.

The default list right now will be 0 (overworld), 6 (Aroma1997 mining world), -11325 (deep dark) and -9999 (Extra Utils quarry), and this list can be edited freely :)

**Comment by BrewAndCode** [comment] 2017-05-15 22:29
I love the whitelist option you just mentioned; but for my scenarios a blacklist would be better.   for some reason the new world gen in the latest build is bypassing my cofh worldgen confirms.  I haven't dug too deeply yet.

Also I don't use the default aroma1997 dimension I'd in my packs.   Not sure hard coding it is a good idea

**Comment by turbodiesel4598** [comment] 2017-05-15 23:05
That is strange - as far as a blacklist is concerned... well, ultimately it would make no difference to ore spawning in the Overworld if the problem is there. I guess it's a question of what's worse between having ores generate in worlds where they shouldn't, and having them absent when they shouldn't be.

And having the other dimension numbers there doesn't hurt - it just ignores IDs that aren't there.

**Comment by turbodiesel4598** [comment] 2017-05-19 11:06
How about another config option to select whether it's a whitelist or a blacklist?

**Comment by th4umiel** [comment] 2017-05-22 21:23
Thanks for the solution :)

**Comment by turbodiesel4598** [comment] 2017-09-21 03:06
The blacklist option will be in version 2.4a :)

**Closed by turbodiesel4598** 2017-09-21 03:06 UTC
Labels: 1.10/11.2, addition
